name: edu_firebase
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.5 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  video_player: ^2.2.19
  firebase_core: ^2.22.0
  firebase_auth: ^4.7.3
  cloud_firestore: ^4.8.5
  firebase_storage: ^11.2.6
  image_picker: ^1.0.2
  google_fonts: ^6.1.0
  logger: ^2.0.2+1
  get: 4.6.6
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/icons/
    - assets/images/
  uses-material-design: true

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
          weight: 500

        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700

        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 300

