// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5-46YLmvUKPKpgjNwCOnrYTPA2E-ksQk',
    appId: '1:571402167336:web:9fc2134d4697bd32a0411d',
    messagingSenderId: '571402167336',
    projectId: 'edu-fire-2334b',
    authDomain: 'edu-fire-2334b.firebaseapp.com',
    storageBucket: 'edu-fire-2334b.appspot.com',
    measurementId: 'G-5Q9CV1YP9T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpU62kJrXiltqaKDmyz5T_CxcifwGb67U',
    appId: '1:571402167336:android:2dc182f6c2c87438a0411d',
    messagingSenderId: '571402167336',
    projectId: 'edu-fire-2334b',
    storageBucket: 'edu-fire-2334b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEKYPzRZvu31Crw6ZxGr_KDC6F-16IUlk',
    appId: '1:571402167336:ios:1068cc5ea86c4041a0411d',
    messagingSenderId: '571402167336',
    projectId: 'edu-fire-2334b',
    storageBucket: 'edu-fire-2334b.appspot.com',
    iosBundleId: 'com.example.eduFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEKYPzRZvu31Crw6ZxGr_KDC6F-16IUlk',
    appId: '1:571402167336:ios:ea3bc6458f23575ca0411d',
    messagingSenderId: '571402167336',
    projectId: 'edu-fire-2334b',
    storageBucket: 'edu-fire-2334b.appspot.com',
    iosBundleId: 'com.example.eduFirebase.RunnerTests',
  );
}
